Correctly handle `HTTPError` in :func:`pytest.raises` for Python <= 3.9.
